#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  7 10:25:25 2019

@author: Ben
"""

import matplotlib.pyplot as plt
import glob
import numpy
import statsClass
import math


arrOfStocks = (glob.glob("/Users/Satan/Desktop/data/*.csv"))

expArr = []
varArr = []
volArr = []

#print(arrOfStocks[1])
# This opens a file and converts every line into an array
#print('expectation', 'variance', 'volatility')
i = 0
while i < len(arrOfStocks):
    fdummy = open(arrOfStocks[i], "r")
    if fdummy.mode == 'r':
        stockArr = []
        for line in fdummy:
            stockArr.append(line)
                
    tempArr = []
    tempArr = statsClass.stringSplitter(stockArr)
        
    expArr.append(statsClass.expectation(tempArr))
    varArr.append(statsClass.variance(tempArr))
    volArr.append(math.sqrt(varArr[i]))
    i = i + 1

i = 0    
while i < len(arrOfStocks):
    #print("%.6f" % expArr[i], "%.6f" % varArr[i], "%.6f" % volArr[i], arrOfStocks[i].split('/')[-1])
    i = i + 1
    
plt.plot(varArr, expArr, marker = 'o', linestyle='None')
plt.xlabel('variance')
plt.ylabel('mean')

arrA = [1, 2, 3, 4, 5, 6]
arrB = [2, 3, 6, 8, 2, 1]
cov = statsClass.covariance(arrA, arrB)
#print(cov)
